package hbidemo.core.NewEmployeeOnboarding.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "lvmh_neo_check_ad")
public class NeoCheckAd extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_NAME = "name";
     public static final String FIELD_VALUE = "value";
     public static final String FIELD_NUM = "num";


     @Id
     @GeneratedValue
     private Long id;

     @Length(max = 255)
     private String name;

     @Length(max = 255)
     private String value;

     @Length(max = 255)
     private String num;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setValue(String value){
         this.value = value;
     }

     public String getValue(){
         return value;
     }

     public void setNum(String num){
         this.num = num;
     }

     public String getNum(){
         return num;
     }

     }
