package hbidemo.core.NewEmployeeOnboarding.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "lvmh_neo_set")
public class NeoSet extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_NAME = "name";
     public static final String FIELD_REQUIRED = "required";
     public static final String FIELD_NO = "no";
     public static final String FIELD_FLAG = "flag";
     public static final String FIELD_TYPE = "type";


     @Id
     @GeneratedValue
     private Long id;

     @Length(max = 255)
     private String name;

     @Length(max = 255)
     private String required;

     private Long no;

     @Length(max = 255)
     private String flag;

     @Length(max = 255)
     private String type;

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setRequired(String required){
         this.required = required;
     }

     public String getRequired(){
         return required;
     }

     public void setNo(Long no){
         this.no = no;
     }

     public Long getNo(){
         return no;
     }

     public void setFlag(String flag){
         this.flag = flag;
     }

     public String getFlag(){
         return flag;
     }

     }
