package hbidemo.core.test3.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "supplier_picture")
public class Picture extends BaseDTO {

     public static final String FIELD_PICTURE_ID = "pictureId";
     public static final String FIELD_SUPPLIER_ID = "supplierId";
     public static final String FIELD_PIC_NAME = "picName";
     public static final String FIELD_PIC_SIZE = "picSize";
     public static final String FIELD_PIC_TYPE = "picType";
     public static final String FIELD_PIC_PATH = "picPath";
     public static final String FIELD_PIC_SAVE_DATE = "picSaveDate";


     @Id
     @GeneratedValue
     private Long pictureId; //图片id

     private Long supplierId; //供应商id

     @Length(max = 30)
     private String picName; //图片名称

     @NotEmpty
     @Length(max = 30)
     private String picSize; //图片大小

     @NotEmpty
     @Length(max = 30)
     private String picType; //图片类型

     @NotEmpty
     @Length(max = 200)
     private String picPath; //图片路径

     private Date picSaveDate; //图片存储时间


     public void setPictureId(Long pictureId){
         this.pictureId = pictureId;
     }

     public Long getPictureId(){
         return pictureId;
     }

     public void setSupplierId(Long supplierId){
         this.supplierId = supplierId;
     }

     public Long getSupplierId(){
         return supplierId;
     }

     public void setPicName(String picName){
         this.picName = picName;
     }

     public String getPicName(){
         return picName;
     }

     public void setPicSize(String picSize){
         this.picSize = picSize;
     }

     public String getPicSize(){
         return picSize;
     }

     public void setPicType(String picType){
         this.picType = picType;
     }

     public String getPicType(){
         return picType;
     }

     public void setPicPath(String picPath){
         this.picPath = picPath;
     }

     public String getPicPath(){
         return picPath;
     }

     public void setPicSaveDate(Date picSaveDate){
         this.picSaveDate = picSaveDate;
     }

     public Date getPicSaveDate(){
         return picSaveDate;
     }

     }
