package hbidemo.core.test2.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.core.annotation.Children;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import java.util.List;

import org.hibernate.validator.constraints.NotEmpty;
import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.core.annotation.MultiLanguage;


@MultiLanguage
@ExtensionAttribute(disable=true)
@Table(name = "sales_header_b")
public class HeaderB extends BaseDTO {

     public static final String FIELD_SALES_ID = "salesId";
     public static final String FIELD_SALES_NUM = "salesNum";
     public static final String FIELD_SHOP_NUM = "shopNum";
     public static final String FIELD_SHOP_NAME = "shopName";
     public static final String FIELD_AMOUNT = "amount";
     public static final String FIELD_SALE_DATE = "saleDate";


     @Id
     @GeneratedValue
     private Long salesId; //销售头ID

     @NotEmpty
     @Length(max = 50)
     private String salesNum; //销售头编码

     @NotEmpty
     @Length(max = 30)
     private String shopNum; //店铺号

     @NotEmpty
     @Length(max = 200)
     @MultiLanguageField
     private String shopName; //店铺名称

     private Long amount; //金额

     private Date saleDate; //销售日期


    @Children
    @Transient  //表示该数据不是 数据表里的字段,同时get和set也要重新设置
    private List<Lines> lines;



     public void setSalesId(Long salesId){
         this.salesId = salesId;
     }

     public Long getSalesId(){
         return salesId;
     }

     public void setSalesNum(String salesNum){
         this.salesNum = salesNum;
     }

     public String getSalesNum(){
         return salesNum;
     }

     public void setShopNum(String shopNum){
         this.shopNum = shopNum;
     }

     public String getShopNum(){
         return shopNum;
     }

     public void setShopName(String shopName){
         this.shopName = shopName;
     }

     public String getShopName(){
         return shopName;
     }

     public void setAmount(Long amount){
         this.amount = amount;
     }

     public Long getAmount(){
         return amount;
     }

     public void setSaleDate(Date saleDate){
         this.saleDate = saleDate;
     }

     public Date getSaleDate(){
         return saleDate;
     }

     public void setLines (List<Lines> lines){
         this.lines = lines;
     }

     public List<Lines> getLines(){
         return lines;
     }

}
