package hbidemo.core.test2.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "sales_lines")
public class Lines extends BaseDTO {

     public static final String FIELD_SALES_LINE_ID = "salesLineId";
     public static final String FIELD_SALES_HEADER_ID = "salesHeaderId";
     public static final String FIELD_COMMODITY_NUM = "commodityNum";
     public static final String FIELD_COMMODITY_NAME = "commodityName";
     public static final String FIELD_SALE_AMOUNT = "saleAmount";


     @Id
     @GeneratedValue
     private Long salesLineId; //销售行ID

     @NotNull
     private Long salesHeaderId; //销售头编码

     @NotEmpty
     @Length(max = 50)
     private String commodityNum; //商品编号

     @NotEmpty
     @Length(max = 30)
     private String commodityName; //商品名称

     private Long saleAmount; //销售金额


     public void setSalesLineId(Long salesLineId){
         this.salesLineId = salesLineId;
     }

     public Long getSalesLineId(){
         return salesLineId;
     }

     public void setSalesHeaderId(Long salesHeaderId){
         this.salesHeaderId = salesHeaderId;
     }

     public Long getSalesHeaderId(){
         return salesHeaderId;
     }

     public void setCommodityNum(String commodityNum){
         this.commodityNum = commodityNum;
     }

     public String getCommodityNum(){
         return commodityNum;
     }

     public void setCommodityName(String commodityName){
         this.commodityName = commodityName;
     }

     public String getCommodityName(){
         return commodityName;
     }

     public void setSaleAmount(Long saleAmount){
         this.saleAmount = saleAmount;
     }

     public Long getSaleAmount(){
         return saleAmount;
     }

     }
